/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
module.exports = {
    RECIPE_EN_US: {
      'Acid Arrow': 'Ranged touch attack; 2d4 damage for 1 round + 1 round/3 levels.',
      'Acid Fog': 'Fog deals acid damage.',
      'Acid Splash': 'Orb deals 1d3 acid damage.',
      'Aid': '+1 on attack rolls and saves against fear, 1d8 temporary hp +1/level (max +10).',
      'Air Walk': 'Subject treads on air as if solid (climb or descend at 45-degree angle).',
      'Alarm': 'Wards an area for 2 hours/level.',
      'Align Weapon': 'Weapon becomes good, evil, lawful, or chaotic.',
      'Alter Self': 'Assume form of a Small or Medium humanoid.',
      'Analyze Dweomer': 'Reveals magical aspects of subject.',
      'Animal Growth': 'One animal doubles in size.',
      'Animal Messenger': 'Sends a Tiny animal to a specific place.',
      'Animal Shapes': 'One ally/level polymorphs into chosen animal.',
      'Animal Trance': 'Fascinates 2d6 HD of animals.',
      'Animate Dead': 'Creates undead skeletons and zombies.',
      'Animate Objects': 'Objects attack your foes.',
      'Animate Plants': 'One or more plants animate and fight for you.',
      'Animate Rope': 'Makes a rope move at your command.',
      'Antilife Shell': '10-ft.-radius field hedges out living creatures.',
      'Antimagic Field': 'Negates magic within 10 ft.',
      'Antipathy': 'Object or location affected by spell repels certain creatures.',
      'Antiplant Shell': 'Keeps animated plants at bay.',
      'Arcane Eye': 'Invisible floating eye moves 30 ft./round.',
      'Arcane Lock': 'Magically locks a portal or chest.',
      'Arcane Mark': 'Inscribes a personal rune on an object or creature (visible or invisible).',
      'Arcane Sight': 'Magical auras become visible to you.',
      'Arcane Sight, Greater': 'As <i><a href="spells/arcaneSight.html#_arcane-sight">arcane sight</a></i>, but also reveals magic effects on creatures and objects.',
      'Astral Projection': 'Projects you and companions onto Astral Plane.',
      'Atonement': 'Removes burden of misdeeds from subject.',
      'Augury': 'Learns whether an action will be good or bad.',
      'Awaken': 'Animal or tree gains human intellect.',
      'Baleful Polymorph': 'Turns subject into harmless animal.',
      'Bane': 'Enemies take –1 on attack rolls and saves against fear.',
      'Banishment': 'Banishes 2 HD/level of extraplanar creatures.',
      'Barkskin': 'Grants +2 (or higher) enhancement to natural armor.',
      'Bear\'s Endurance': 'Subject gains +4 to <a href="gettingStarted.html#_constitution">Con</a> for 1 min./level.',
      'Bear\'s Endurance, Mass': 'As <i><a href="spells/bearSEndurance.html#_bear-s-endurance">bear\'s endurance</a></i>, affects one subject/level.',
      'Beast Shape I': 'You take the form and some of the powers of a Small or Medium animal.',
      'Beast Shape II': 'You take the form and some of the powers of a Tiny or Large animal.',
      'Beast Shape III': 'You take the form of a Diminutive or Huge animal, or Small or Medium magical beast.',
      'Beast Shape IV': 'You take the form of a Diminutive to Huge animal or a Tiny to Large magical beast.',
      'Bestow Curse': '&#8211;6 to an ability score; &#8211;4 on attack rolls, saves, and checks; or 50% chance of losing each action.',
      'Binding': 'As <i><a href="../spells/planarBinding.html#_planar-binding-lesser">lesser planar binding</a></i>, but up to 18 HD.',
      'Black Tentacles': 'Tentacles grapple all creatures within a 20-ft. spread.',
      'Blade Barrier': 'Wall of blades deals 1d6/level damage.',
      'Blasphemy': 'Kills, paralyzes, weakens, or dazes nonevil subjects.',
      'Bleed': 'Cause a stabilized creature to resume <a href="glossary.html#_dying">dying</a>.',
      'Bless': 'Allies gain +1 on attack rolls and saves against fear.',
      'Bless Water': 'Makes holy water.',
      'Bless Weapon': 'Weapon strikes true against evil foes.',
      'Blight': 'Withers one plant or deals 1d6/level damage to plant creature.',
      'Blindness/Deafness': 'Makes subject blind or deaf.',
      'Blink': 'You randomly vanish and reappear for 1 round per level.',
      'Blur': 'Attacks miss subject 20% of the time.',
      'Break Enchantment': 'Frees subjects from enchantments, transmutations, and curses.',
      'Breath of Life': 'Cures 5d8 damage + 1/level and restores life to recently slain creatures.',
      'Bull\'s Strength': 'Subject gains +4 to Str for 1 min./level.',
      'Bull\'s Strength, Mass': 'As <i><a href="spells/bullSStrength.html#_bull-s-strength">bull\'s strength</a></i>, affects 1 subject per level.',
      'Burning Hands': '1d4/level fire damage (max 5d4).',
      'Call Lightning': 'Calls down lightning bolts (3d6 per bolt) from sky.',
      'Call Lightning Storm': 'As <i><a href="spells/callLightning.html#_call-lightning">call lightning</a>, </i>but 5d6 damage per bolt.',
      'Calm Animals': 'Calms 2d4 + level HD of animals.',
      'Calm Emotions': 'Calms creatures, negating emotion effects.',
      'Cat\'s Grace': 'Subject gains +4 to <a href="gettingStarted.html#_dexterity">Dex</a> for 1 min./level.',
      'Cat\'s Grace, Mass': 'As <i><a href="spells/catSGrace.html#_cat-s-grace">cat\'s grace</a></i>, affects 1 subject/level.',
      'Cause Fear': 'A creature of 5 HD or less flees for 1d4 rounds.',
      'Chain Lightning': '1d6/level damage, 1 more bolt/level.',
      'Changestaff': 'Your staff becomes a treant on command.',
      'Chaos Hammer': 'Harms and slows lawful creatures (1d8 damage/2 levels).',
      'Charm Animal': 'Makes one animal your friend.',
      'Charm Monster': 'Makes monster believe it is your ally.',
      'Charm Monster, Mass': 'As <i><a href="spells/charmMonster.html#_charm-monster">charm monster</a>, </i>but all within 30 ft.',
      'Charm Person': 'Makes one person your friend.',
      'Chill Metal': 'Cold metal damages those who touch it.',
      'Chill Touch': 'One touch/level deals 1d6 damage and possibly 1 <a href="gettingStarted.html#_strength">Str</a> damage.',
      'Circle of Death': 'Kills 1d4/level HD of creatures.',
      'Clairaudience/Clairvoyance': 'Hear or see at a distance for 1 min./level.',
      'Clenched Fist': 'Large hand provides cover, pushes, or attacks your foes.',
      'Cloak of Chaos': '+4 to <a href="combat.html#_armor-class">AC</a>, +4 resistance, and SR 25 against lawful spells.',
      'Clone': 'Duplicate awakens when original dies.',
      'Cloudkill': 'Kills 3 HD or less; 4&#8211;6 HD save or die; 6+ HD take Con damage.',
      'Color Spray': 'Knocks <a href="glossary.html#_unconscious">unconscious</a>, blinds, and/or stuns weak creatures.',
      'Command': 'One subject obeys a command for 1 round.',
      'Command, Greater': 'As <i><a href="spells/command.html#_command">command</a>, </i>but affects one subject/level.',
      'Command Plants': 'Sway the actions of plant creatures.',
      'Command Undead': 'Undead creature obeys your commands.',
      'Commune': 'Deity answers one yes-or-no question/level.',
      'Commune with Nature': 'Learn about terrain for 1 mile/level.',
      'Comprehend Languages': 'You understand all spoken and written languages.',
      'Cone of Cold': '1d6/level cold damage.',
      'Confusion': 'Subjects behave oddly for 1 round/level.',
      'Confusion, Lesser': 'One creature is <i><a href="glossary.html#_confused">confused</a> </i>for 1 round.',
      'Consecrate': 'Fills area with positive energy, weakening undead.',
      'Contact Other Plane': 'Lets you ask question of extraplanar entity.',
      'Contagion': 'Infects subject with chosen disease.',
      'Contingency': 'Sets trigger condition for another spell.',
      'Continual Flame': 'Makes a permanent, heatless light.',
      'Control Plants': 'Controls actions of one or more plant creatures.',
      'Control Undead': 'Undead don\'t attack you while under your command.',
      'Control Water': 'Raises or lowers bodies of water.',
      'Control Weather': 'Changes weather in local area.',
      'Control Winds': 'Changes wind direction and speed.',
      'Create Food and Water': 'Feeds three humans (or one horse)/level.',
      'Create Greater Undead': 'Creates shadows, wraiths, spectres, or devourers.',
      'Create Undead': 'Raises ghouls, ghasts, mummies, or mohrgs from physical remains.',
      'Create Water': 'Creates 2 gallons/level of pure water.',
      'Creeping Doom': 'Swarms of centipedes attack at your command.',
      'Crushing Despair': 'Subjects take –2 on attack rolls, damage rolls, saves, and checks.',
      'Crushing Hand': 'Large hand provides cover, pushes, or crushes your foes.',
      'Cure Critical Wounds': 'Cures 4d8 damage + 1/level (max +20).',
      'Cure Critical Wounds, Mass': 'Cures 4d8 damage + 1/level for many creatures.',
      'Cure Light Wounds': 'Cures 1d8 damage + 1/level (max +5).',
      'Cure Light Wounds, Mass': 'Cures 1d8 damage + 1/level, affects 1 subject/level.',
      'Cure Moderate Wounds': 'Cures 2d8 damage +1/level (max. +10).',
      'Cure Moderate Wounds, Mass': 'Cures 2d8 damage + 1/level, affects 1 subject/level.',
      'Cure Serious Wounds': 'Cures 3d8 damage + 1/level (max +15).',
      'Cure Serious Wounds, Mass': 'Cures 3d8 damage + 1/level, affects 1 subject/level.',
      'Curse Water': 'Makes water unholy.',
      'Dancing Lights': 'Creates torches or other lights.',
      'Darkness': '20-ft. radius of supernatural shadow.',
      'Darkvision': 'See 60 ft. in total darkness.',
      'Daylight': '60-ft. radius of bright light.',
      'Daze': 'A single humanoid creature with 4 HD or less loses its next action.',
      'Daze Monster': 'Living creature of 6 HD or less loses its next action.',
      'Death Knell': 'Kills dying creature; you gain 1d8 temporary hp, +2 to Str, and +1 caster level.',
      'Death Ward': 'Grants bonuses against death spells and negative energy.',
      'Deathwatch': 'Reveals how near death subjects within 30 ft. are.',
      'Deeper Darkness': 'Object sheds shadows in 60-ft. radius.',
      'Deep Slumber': 'Puts 10 HD of creatures to <a href="spells/sleep.html#_sleep">sleep</a>.',
      'Delayed Blast Fireball': '1d6/level fire damage; you can postpone blast for up to 5 rounds.',
      'Delay Poison': 'Stops poison from harming subject for 1 hour/level.',
      'Demand': 'As <i><a href="spells/sending.html#_sending">sending</a>, </i>plus you can send <i><a href="spells/suggestion.html#_suggestion">suggestion</a>.</i>',
      'Desecrate': 'Fills area with negative energy; aids undead.',
      'Destruction': 'Kills subject and destroys remains.',
      'Detect Animals or Plants': 'Detects kinds of animals or plants.',
      'Detect Chaos': 'Reveals creatures, spells, or objects of selected alignment.',
      'Detect Evil': '',
      'Detect Good': '',
      'Detect Law': '',
      'Detect Magic': 'Detects all spells and magic items within 60 ft.',
      'Detect Poison': 'Detects poison in a creature or object.',
      'Detect Scrying': 'Alerts you to magical eavesdropping',
      'Detect Secret Doors': 'Reveals hidden doors within 60 ft.',
      'Detect Snares and Pits': 'Reveals natural or primitive traps.',
      'Detect Thoughts': 'Allows “listening” to surface thoughts.',
      'Detect Undead': 'Reveals undead within 60 ft.',
      'Dictum': 'Kills, paralyzes, staggers, or deafens nonlawful targets.',
      'Dimensional Anchor': 'Bars extradimensional movement.',
      'Dimensional Lock': 'Teleportation and interplanar travel blocked for 1 day/level.',
      'Dimension Door': 'Teleports you a short distance.',
      'Diminish Plants': 'Reduces size or blights growth of normal plants.',
      'Discern Lies': 'Reveals deliberate falsehoods.',
      'Discern Location': 'Reveals exact location of creature or object.',
      'Disguise Self': 'Changes your appearance.',
      'Disintegrate': 'Reduces one creature or object to dust.',
      'Dismissal': 'Forces a creature to return to its native plane.',
      'Dispel Chaos': '+4 bonus against attacks by chaotic creatures.',
      'Dispel Evil': '+4 bonus against attacks by evil creatures.',
      'Dispel Good': '+4 against attacks by good creatures.',
      'Dispel Law': '+4 against attacks by lawful creatures.',
      'Dispel Magic': 'Cancels one magical spell or effect.',
      'Dispel Magic, Greater': 'As <i><a href="spells/dispelMagic.html#_dispel-magic">dispel magic</a></i>, but with multiple targets.',
      'Displacement': 'Attacks miss subject 50% of the time.',
      'Disrupting Weapon': 'Melee weapon destroys undead.',
      'Disrupt Undead': 'Deals 1d6 damage to one undead.',
      'Divination': 'Provides useful advice for specific proposed actions.',
      'Divine Favor': 'You gain +1 per three levels on attack and damage rolls.',
      'Divine Power': 'You gain attack bonuses and 1 hp/level.',
      'Dominate Animal': 'One animal obeys your silent mental commands and orders.',
      'Dominate Monster': 'As <i><a href="spells/dominatePerson.html#_dominate-person">dominate person</a>, </i>but any creature.',
      'Dominate Person': 'Controls humanoid telepathically.',
      'Doom': 'One subject takes &#8211;2 on attack rolls, damage rolls, saves, and checks.',
      'Dream': 'Sends message to anyone sleeping.',
      'Eagle\'s Splendor': 'Subject gains +4 to Cha for 1 min./level.',
      'Eagle\'s Splendor, Mass': 'As <i><a href="spells/eagleSSplendor.html#_eagle-s-splendor">eagle\'s splendor</a></i>, 1 subject/level.',
      'Earthquake': 'Intense tremor shakes 80-ft.-radius.',
      'Elemental Body I': 'Turns you into a Small elemental.',
      'Elemental Body II': 'You become a Medium elemental.',
      'Elemental Body III': 'Turns you into a Large elemental.',
      'Elemental Body IV': 'Turns you into a Huge elemental.',
      'Elemental Swarm': 'Summons multiple elementals.',
      'Endure Elements': 'Exist comfortably in hot or cold regions.',
      'Energy Drain': 'Subject gains 2d4 <a href="glossary.html#_energy-drain-and-negative-levels">negative levels</a>.',
      'Enervation': 'Subject gains 1d4 <a href="glossary.html#_energy-drain-and-negative-levels">negative levels</a>.',
      'Enlarge Person': 'Humanoid creature doubles in size.',
      'Enlarge Person, Mass': '1 humanoid creature/level doubles in size.',
      'Entangle': 'Plants entangle everyone in 40-ft. radius.',
      'Enthrall': 'Captivates all within 100 ft. + 10 ft./level.',
      'Entropic Shield': 'Ranged attacks against you have 20% miss chance.',
      'Erase': 'Mundane or magical writing vanishes.',
      'Ethereal Jaunt': 'You become ethereal for 1 round/level.',
      'Etherealness': 'Travel to Ethereal Plane with companions.',
      'Expeditious Retreat': 'Your base speed increases by 30 ft.',
      'Explosive Runes': 'Deals 6d6 damage when read.',
      'Eyebite': 'Target becomes <a href="glossary.html#_panicked">panicked</a>, <a href="glossary.html#_sickened">sickened</a>, and comatose.',
      'Fabricate': 'Transforms raw materials into finished items.',
      'Faerie Fire': 'Outlines subjects with light, canceling <i><a href="spells/blur.html#_blur">blur</a></i>, concealment, and the like.',
      'False Life': 'Gain 1d10 temporary hp + 1/level (max +10).',
      'False Vision': 'Fools <a href="spells/scrying.html#_scrying">scrying</a> with an illusion.',
      'Fear': 'Subjects within cone flee for 1 round/level.',
      'Feather Fall': 'Objects or creatures fall slowly.',
      'Feeblemind': 'Subject\'s <a href="gettingStarted.html#_intelligence">Int</a> and <a href="gettingStarted.html#_charisma-new">Cha</a> drop to 1.',
      'Find the Path': 'Shows most direct way to a location.',
      'Find Traps': 'Notice traps as a rogue does.',
      'Finger of Death': 'Deals 10 damage/level to one subject.',
      'Fireball': '1d6 fire damage per level, 20-ft. radius.',
      'Fire Seeds': 'Acorns and berries become grenades and bombs.',
      'Fire Shield': 'Creatures attacking you take fire damage; you\'re protected from heat or cold.',
      'Fire Storm': 'Deals 1d6/level fire damage.',
      'Fire Trap': 'Opened object deals 1d4 damage +1/level.',
      'Flame Arrow': 'Arrows deal +1d6 fire damage.',
      'Flame Blade': 'Touch attack deals 1d8 + 1/two levels damage.',
      'Flame Strike': 'Smites foes with divine fire (1d6/level damage).',
      'Flaming Sphere': 'Ball of fire deals 3d6 fire damage.',
      'Flare': 'Dazzles one creature (–1 on attack rolls).',
      'Flesh to Stone': 'Turns subject creature into statue.',
      'Floating Disk': 'Creates 3-ft.-diameter horizontal disk that holds 100 lbs./level.',
      'Fly': 'Fog obscures vision.',
      'Fog Cloud': 'Fog obscures vision.',
      'Forbiddance': 'Blocks planar travel, damages creatures of different alignment.',
      'Forcecage': 'Cube or cage of force imprisons all inside.',
      'Forceful Hand': 'Hand pushes creatures away.',
      'Foresight': '“Sixth sense” warns of impending danger.',
      'Form of the Dragon I': 'Turns you into a Medium dragon.',
      'Form of the Dragon II': 'Turns you into a Large dragon.',
      'Form of the Dragon III': 'Turns you into a Huge dragon.',
      'Fox\'s Cunning': 'Subject gains +4 to <a href="gettingStarted.html#_intelligence">Int</a> for 1 min./level.',
      'Fox\'s Cunning, Mass': 'As <i><a href="spells/foxSCunning.html#_fox-s-cunning">fox\'s cunning</a></i>, affects 1 subject/ level.',
      'Freedom': 'Releases creature from <i><a href="spells/imprisonment.html#_imprisonment">imprisonment</a>.</i>',
      'Freedom of Movement': 'Subject moves normally despite impediments to movement.',
      'Freezing Sphere': 'Freezes water or deals cold damage.',
      'Gaseous Form': 'Become insubstantial and fly slowly.',
      'Gate': 'Connects two planes for travel or summoning.',
      'Geas, Lesser': 'Commands subject of 7 HD or less.',
      'Geas/Quest': 'As <i>lesser geas, </i>but affects any creature.',
      'Gentle Repose': 'Preserves one corpse.',
      'Ghost Sound': 'Figment sounds.',
      'Ghoul touch': 'Paralyzes one subject, which exudes stench that makes those nearby <a href="glossary.html#_sickened">sickened</a>.',
      'Giant Form I': 'Turns you into a Large giant.',
      'Giant Form II': 'Turns you into a Huge giant.',
      'Giant Vermin': 'Turns centipedes, scorpions, or spiders into giant vermin.',
      'Glibness': 'You gain +20 bonus on Bluff checks, and your lies can escape magical discernment.',
      'Glitterdust': 'Blinds targets, outlines invisible things.',
      'Globe of Invulnerability': 'As <i><a href="spells/globeOfInvulnerability.html#_globe-of-invulnerability-lesser">lesser globe of invulnerability</a></i>, plus 4th-level spell effects.',
      'Globe of Invulnerability, Lesser': 'Stops 1st- through 3rd-level spell effects.',
      'Glyph of Warding': 'Inscription harms those who pass it.',
      'Glyph of Warding, Greater': 'As <i><a href="spells/glyphOfWarding.html#_glyph-of-warding">glyph of warding</a></i>, but up to 10d8 damage or 6th-level spell.',
      'Goodberry': '2d4 berries each cure 1 hp (max 8 hp/24 hours).',
      'Good Hope': 'Subjects gain +2 on attack rolls, damage rolls, saves, and checks.',
      'Grasping Hand': 'Hand provides cover, pushes, or grapples.',
      'Grease': 'Makes 10-ft. square or one object slippery.',
      'Guards and Wards': 'Array of magic effects protect area.',
      'Guidance': '+1 on one attack roll, saving throw, or skill check.',
      'Gust of Wind': 'Blast of wind blows away or knocks down creatures.',
      'Hallow': 'Designates location as holy.',
      'Hallucinatory Terrain': 'Makes one type of terrain appear like another (field as forest, or the like).',
      'Halt Undead': 'Immobilizes undead for 1 round/level.',
      'Harm': 'Deals 10 points/level damage to target.',
      'Haste': 'One creature/level moves faster, +1 on attack rolls, <a href="combat.html#_armor-class">AC</a>, and <a href="combat.html#_reflex">Reflex</a> saves.',
      'Heal': 'Cures 10 points/level damage, all diseases and mental conditions.',
      'Heal, Mass': 'As <i><a href="spells/heal.html#_heal">heal</a></i>, but affects 1 subject/level.',
      'Heal Mount': 'As <i><a href="spells/heal.html#_heal">heal</a> </i>on horse or other special mount.',
      'Heat Metal': 'Makes metal so hot it damages those who touch it.',
      'Helping Hand': 'Ghostly hand leads subject to you.',
      'Heroes\' Feast': 'Food for one creature/level cures and grants combat bonuses<i>.</i>',
      'Heroism': 'Gives +2 bonus on attack rolls, saves, skill checks.',
      'Heroism, Greater': 'Gives +4 bonus on attack rolls, saves, skill checks; immunity to fear; temporary hp.',
      'Hide from Animals': 'Animals can\'t perceive one subject/level.',
      'Hide from Undead': 'Undead can\'t perceive one subject/level.',
      'Hideous Laughter': 'Subject loses actions for 1 round/level.',
      'Hold Animal': 'Paralyzes one animal for 1 round/level.',
      'Hold Monster': 'As <i><a href="spells/holdPerson.html#_hold-person">hold person</a></i>, but any creature.',
      'Hold Monster, Mass': 'As <i><a href="spells/holdMonster.html#_hold-monster">hold monster</a>, </i>but all within 30 ft.',
      'Hold Person': 'Paralyzes one humanoid for 1 round/level.',
      'Hold Person, Mass': 'As <i><a href="spells/holdPerson.html#_hold-person">hold person</a></i>, but all within 30 ft.',
      'Hold Portal': 'Holds door shut.',
      'Holy Aura': '+4 to <a href="combat.html#_armor-class">AC</a>, +4 resistance, and SR 25 against evil spells.',
      'Holy Smite': 'Harms and possibly blinds evil creatures (1d8 damage/2 levels).',
      'Holy Sword': 'Weapon becomes +5, deals +2d6 damage against evil.',
      'Holy Word': 'Kills, paralyzes, blinds, or deafens nongood subjects.',
      'Horrid Wilting': 'Deals 1d6/level damage within 30 ft.',
      'Hypnotic Pattern': 'Fascinates 2d4 + level HD of creatures.',
      'Hypnotism': 'Fascinates 2d4 HD of creatures.',
      'Ice Storm': 'Hail deals 5d6 damage in area 40 ft. across.',
      'Identify': 'Gives +10 bonus to identify magic items.',
      'Illusory Script': 'Only select creatures can read text.',
      'Illusory Wall': 'Wall, floor, or ceiling looks real, but anything can pass through.',
      'Imbue with Spell Ability': 'Transfer spells to subject.',
      'Implosion': 'Inflict 10 damage/level to one creature/round.',
      'Imprisonment': 'Entombs subject beneath the earth.',
      'Incendiary Cloud': 'Deals 6d6 fire damage/round.',
      'Inflict Critical Wounds': 'Touch attack, 4d8 damage + 1/level (max +20).',
      'Inflict Critical Wounds, Mass': 'Deals 4d8 damage + 1/level, affects 1 subject/level.',
      'Inflict Light Wounds': 'Touch deals 1d8 damage +1/level (max +5).',
      'Inflict Light Wounds, Mass': 'Deals 1d8 damage + 1/level, affects 1 subject/level.',
      'Inflict Moderate Wounds': 'Touch attack, 2d8 damage +1/level (max +10).',
      'Inflict Moderate Wounds, Mass': '',
      'Inflict Serious Wounds': 'Touch attack, 3d8 damage +1/level (max +15).',
      'Inflict Serious Wounds, Mass': 'Deals 3d8 damage + 1/level, affects 1 subject/level.',
      'Insanity': 'Subject suffers continuous <i><a href="spells/confusion.html#_confusion">confusion</a></i>.',
      'Insect Plague': 'Wasp swarms attack creatures.',
      'Instant Summons': 'Prepared object appears in your hand.',
      'Interposing Hand': 'Hand provides cover against 1 opponent.',
      'Invisibility': 'Subject is invisible for 1 min./level or until it attacks.',
      'Invisibility, Greater': 'As <i><a href="../spells/invisibility.html#_invisibility">invisibility</a></i>, but subject can attack and stay invisible.',
      'Invisibility, Mass': 'As <i><a href="spells/invisibility.html#_invisibility">invisibility</a></i>, but affects all in range.',
      'Invisibility Purge': 'Dispels invisibility within 5 ft./level.',
      'Invisibility Sphere': 'Makes everyone within 10 ft. <a href="glossary.html#_invisible">invisible</a>.',
      'Iron Body': 'Your body becomes living iron.',
      'Ironwood': 'Magic wood is as strong as steel.',
      'Irresistible Dance': 'Forces subject to dance.',
      'Jump': 'Subject gets bonus on Acrobatics checks.',
      'Keen Edge': 'Doubles normal weapon\'s threat range.',
      'Knock': 'Opens locked or magically sealed door.',
      'Know Direction': 'You discern north.',
      'Legend Lore': 'Lets you learn tales about a person, place, or thing.',
      'Levitate': 'Subject moves up and down at your direction.',
      'Light': 'Object shines like a torch.',
      'Lightning Bolt': 'Electricity deals 1d6/level damage.',
      'Limited Wish': 'Alters reality (within limits).',
      'Liveoak': 'Oak becomes treant guardian.',
      'Locate Creature': 'Indicates direction to familiar creature.',
      'Locate Object': 'Senses direction toward object (specific or type).',
      'Longstrider': 'Your base speed increases by 10 ft.',
      'Lullaby': 'Makes subject drowsy',
      'Mage Armor': 'Gives subject +4 armor bonus.',
      'Mage Hand': '5-pound telekinesis.',
      'Mage\'s Disjunction': 'Dispels magic, disenchants magic items.',
      'Mage\'s Faithful Hound': 'Phantom dog can guard a location and attack intruders.',
      'Mage\'s Lucubration': '<i>Wizard only. </i>Recalls spell of 5th level or lower.',
      'Mage\'s Magnificent Mansion': 'Door leads to extradimensional mansion.',
      'Mage\'s Private Sanctum': 'Prevents anyone from viewing or <a href="spells/scrying.html#_scrying">scrying</a> an area for 24 hours.',
      'Mage\'s Sword': 'Floating magic blade strikes opponents.',
      'Magic Aura': 'Alters object\'s magic aura.',
      'Magic Circle against Chaos': 'As <i>protection </i>spells, but 10-ft. radius and 10 min./level.',
      'Magic Circle against Evil': 'As <i><a href="spells/protectionFromChaos.html#_protection-from-chaos">protection from chaos</a></i>, but 10-ft. radius and 10 min./level.',
      'Magic Circle against Good': 'As <i>protection </i>spells, but 10-ft. radius and 10 min./level.',
      'Magic Circle against Law': '',
      'Magic Fang': 'One natural weapon of subject creature gets +1 on attack and damage rolls.',
      'Magic Fang, Greater': 'One natural weapon gets + 1/four levels (max. +5).',
      'Magic Jar': 'Enables possession of another creature.',
      'Magic Missile': '1d4+1 damage; +1 missile per two levels above 1st (max 5).',
      'Magic Mouth': 'Object speaks once when triggered.',
      'Magic Stone': 'Three stones gain +1 on attack rolls, deal 1d6+1 damage.',
      'Magic Vestment': 'Armor or shield gains +1 enhancement per four levels.',
      'Magic Weapon': 'Weapon gains +1 bonus.',
      'Magic Weapon, Greater': 'Weapon gains +1 bonus/four levels (max +5).',
      'Major Creation': 'As <i><a href="spells/minorCreation.html#_minor-creation">minor creation</a>, </i>plus stone and metal.',
      'Major Image': 'As <i><a href="spells/silentImage.html#_silent-image">silent image</a></i>, plus sound, smell and thermal effects.',
      'Make Whole': 'Repairs an object.',
      'Mark of Justice': 'Designates action that triggers <i>curse </i>on subject.',
      'Maze': 'Traps subject in extradimensional maze.',
      'Meld into Stone': 'You and your gear merge with stone.',
      'Mending': 'Makes minor repairs on an object.',
      'Message': 'Whisper conversation at distance.',
      'Meteor Swarm': 'Four meteors each deal 6d6 fire damage.',
      'Mind Blank': 'Subject is protected from mental/emotional magic and <a href="spells/scrying.html#_scrying">scrying</a>.',
      'Mind Fog': 'Subjects in fog get –10 to <a href="gettingStarted.html#_wisdom">Wis</a> and <a href="combat.html#_will">Will</a> checks.',
      'Minor Creation': 'Creates one cloth or wood object.',
      'Minor Image': 'As <i><a href="spells/silentImage.html#_silent-image">silent image</a></i>, plus some sound.',
      'Miracle': 'Requests a deity\'s intercession.',
      'Mirage Arcana': 'As <i><a href="spells/hallucinatoryTerrain.html#_hallucinatory-terrain">hallucinatory terrain</a>, </i>plus structures.',
      'Mirror Image': 'Creates decoy duplicates of you.',
      'Misdirection': 'Misleads divinations for 1 creature or object.',
      'Mislead': 'Turns you <a href="glossary.html#_invisible">invisible</a> and creates illusory double.',
      'Mnemonic Enhancer': '<i>Wizard only. </i>Prepare extra spells or retain one just cast.',
      'Modify Memory': 'Changes 5 minutes of subject\'s memories.',
      'Moment of Prescience': 'You gain +1/level insight bonus on single attack roll, check, or save.',
      'Mount': 'Summons riding horse for 2 hours/level.',
      'Move Earth': 'Digs trenches and builds hills.',
      'Neutralize Poison': 'Immunizes subject against poison, detoxifies venom in or on subject.',
      'Nightmare': 'Sends vision dealing 1d10 damage, fatigue.',
      'Nondetection': 'Hides subject from divination, scrying.',
      'Obscure Object': 'Masks object against <a href="spells/scrying.html#_scrying">scrying</a>.',
      'Obscuring Mist': 'Fog surrounds you.',
      'Open/Close': 'Opens or closes small or light things.',
      'Order\'s Wrath': 'Harms and dazes chaotic creatures (1d8 damage/2 levels).',
      'Overland Flight': 'You fly at a speed of 40 ft. and can hustle over long distances.',
      'Owl\'s Wisdom': 'Subject gains +4 to <a href="gettingStarted.html#_wisdom">Wis</a> for 1 min./level.',
      'Owl\'s Wisdom, Mass': 'As <i><a href="spells/owlSWisdom.html#_owl-s-wisdom">owl\'s wisdom</a></i>, affects 1 subject/level.',
      'Passwall': 'Creates passage through wood or stone wall.',
      'Pass without Trace': 'One subject/level leaves no tracks.',
      'Permanency': 'Makes certain spells permanent.',
      'Permanent Image': 'Permanent illusion, includes sight, sound, smell, and thermal effects.',
      'Persistent Image': 'As <i><a href="spells/majorImage.html#_major-image">major image</a></i>, but with no concentration required.',
      'Phantasmal Killer': 'Fearsome illusion kills subject or deals 3d6 damage.',
      'Phantom Steed': 'Magic horse appears for 1 hour/level.',
      'Phantom Trap': 'Makes item seem trapped.',
      'Phase Door': 'Creates an <a href="glossary.html#_invisible">invisible</a> passage through a barrier.',
      'Planar Ally': 'As <i><a href="spells/planarAlly.html#_planar-ally-lesser">lesser planar ally</a>, </i>but up to 12 HD.',
      'Planar Ally, Greater': 'As <i><a href="spells/planarAlly.html#_planar-ally-lesser">lesser planar ally</a>, </i>but up to 18 HD.',
      'Planar Ally, Lesser': 'Exchange services with a 6 HD extraplanar creature.',
      'Planar Binding': 'As <i><a href="../spells/planarBinding.html#_planar-binding-lesser">lesser planar binding</a></i>, but up to 12 HD.',
      'Planar Binding, Greater': 'As <i><a href="../spells/planarBinding.html#_planar-binding-lesser">lesser planar binding</a></i>, but up to 18 HD.',
      'Planar Binding, Lesser': 'Traps elemental creature of 6 HD or less until it performs a task.',
      'Plane Shift': 'As many as eight subjects travel to another plane.',
      'Plant Growth': 'Grows vegetation, improves crops.',
      'Plant Shape I': 'Turns you into a Small or Medium plant.',
      'Plant Shape II': 'Turns you into a Large plant creature.',
      'Plant Shape III': 'Turns you into a Huge plant.',
      'Poison': 'Touch deals 1d3 Con damage 1/round for 6 rounds.',
      'Polar Ray': 'Ranged touch attack deals 1d6/level cold damage and 1d4 points of Dexterity drain.',
      'Polymorph Any Object': 'Changes a subject into anything else.',
      'Polymorph': 'Gives one willing subject a new form.',
      'Polymorph, Greater': 'Gives one willing subject a new, more powerful form.',
      'Power Word Blind': 'Blinds creature with 200 hp or less.',
      'Power Word Kill': 'Kills one creature with 100 hp or less.',
      'Power Word Stun': 'Stuns creature with 150 hp or less.',
      'Prayer': 'Allies get +1 bonus on most rolls, enemies –1 penalty.',
      'Prestidigitation': 'Performs minor tricks.',
      'Prismatic Sphere': 'As <i><a href="spells/prismaticWall.html#_prismatic-wall">prismatic wall</a></i>, but surrounds on all sides.',
      'Prismatic Spray': 'Rays hit subjects with variety of effects.',
      'Prismatic Wall': 'Wall\'s colors have array of effects.',
      'Produce Flame': '1d6 damage + 1/level, touch or thrown.',
      'Programmed Image': 'As <i><a href="spells/majorImage.html#_major-image">major image</a></i>, but triggered by event.',
      'Project Image': 'Illusory double can talk and cast spells.',
      'Protection from Arrows': 'Subject gains <a href="glossary.html#_damage-reduction">DR</a> 10/magic against ranged attacks.',
      'Protection from Chaos': '',
      'Protection from Energy': 'Absorbs 12 points/level of damage from one kind of energy.',
      'Protection from Evil': '+2 to <a href="combat.html#_armor-class">AC</a> and saves, plus additional protection against selected alignment.',
      'Protection from Good': '+2 to AC and saves, plus additional protection against selected alignments.',
      'Protection from Law': '',
      'Protection from Spells': 'Confers +8 resistance bonus.',
      'Prying Eyes': '1d4 + 1/level floating eyes scout for you.',
      'Prying Eyes, Greater': 'As <i><a href="spells/pryingEyes.html#_prying-eyes">prying eyes</a></i>, but eyes have <i><a href="spells/trueSeeing.html#_true-seeing">true seeing</a></i>.',
      'Purify Food and Drink': 'Purifies 1 cu. ft./level of food or water.',
      'Pyrotechnics': 'Turns fire into light or thick smoke.',
      'Quench': 'Extinguishes fires.',
      'Rage': 'Gives +2 to <a href="gettingStarted.html#_strength">Str</a> and <a href="gettingStarted.html#_constitution">Con</a>, +1 on <a href="combat.html#_will">Will</a> saves, &#8211;2 to <a href="combat.html#_armor-class">AC</a>.',
      'Rainbow Pattern': 'Lights fascinate 24 HD of creatures.',
      'Raise Dead': 'Restores life to subject who died as long as one day/level ago.',
      'Ray of Enfeeblement': 'Ray causes 1d6 <a href="gettingStarted.html#_strength">Str</a> penalty + 1 per 2 levels.',
      'Ray of Exhaustion': 'Ray makes subject <a href="glossary.html#_exhausted">exhausted</a>.',
      'Ray of Frost': 'Ray deals 1d3 cold damage.',
      'Read Magic': 'Read scrolls and spellbooks.',
      'Reduce Animal': 'Shrinks one willing animal.',
      'Reduce Person': 'Humanoid creature halves in size.',
      'Reduce Person, Mass': 'As <i><a href="spells/reducePerson.html#_reduce-person">reduce person</a></i>, but affects 1 humanoid creature/level.',
      'Refuge': 'Alters item to transport its possessor to your abode.',
      'Regenerate': 'Subject\'s severed limbs grow back, cures 4d8 damage +1/level (max +35).',
      'Reincarnate': 'Brings dead subject back in a random body.',
      'Remove Blindness/Deafness': 'Cures normal or magical blindness or deafness.',
      'Remove Curse': 'Frees object or person from curse.',
      'Remove Disease': 'Cures all diseases affecting subject.',
      'Remove Fear': 'Suppresses fear or gives +4 on saves against fear for one subject + one per four levels.',
      'Remove Paralysis': 'Frees one or more creatures from paralysis or <a href="spells/slow.html#_slow">slow</a> effect.',
      'Repel Metal or Stone': 'Pushes away metal and stone.',
      'Repel Vermin': 'Insects, spiders, and other vermin stay 10 ft. away.',
      'Repel Wood': 'Pushes away wooden objects.',
      'Repulsion': 'Creatures can\'t approach you.',
      'Resilient Sphere': 'Force globe protects but traps one subject.',
      'Resistance': 'Subject gains +1 on saving throws.',
      'Resist Energy': 'Ignores first 10 (or more) points of damage per attack from specified energy type.',
      'Restoration': 'Restores level and ability score drains.',
      'Restoration, Greater': 'As <i><a href="spells/restoration.html#_restoration">restoration</a>, </i>plus restores all levels and ability scores.',
      'Restoration, Lesser': 'Dispels magical ability penalty or repairs 1d4 ability damage.',
      'Resurrection': 'Fully restore dead subject.',
      'Reverse Gravity': 'Objects and creatures fall upward.',
      'Righteous Might': 'Your size increases, and you gain bonuses in combat.',
      'Rope Trick': 'As many as eight creatures hide in extradimensional space.',
      'Rusting Grasp': 'Your touch corrodes iron and alloys.',
      'Sanctuary': 'Opponents can\'t attack you, and you can\'t attack.',
      'Scare': 'Frightens creature of less than 6 HD.',
      'Scintillating Pattern': 'Twisting colors <i>confuse, </i>stun, or render <a href="glossary.html#_unconscious">unconscious</a>.',
      'Scorching Ray': 'Ranged touch attack deals 4d6 fire damage, +1 ray/four levels (max 3).',
      'Screen': 'Illusion hides area from vision and <a href="spells/scrying.html#_scrying">scrying</a>.',
      'Scrying': 'Spies on subject from a distance.',
      'Scrying, Greater': 'As <i><a href="spells/scrying.html#_scrying">scrying</a></i>, but faster and longer.',
      'Sculpt Sound': 'Creates new sounds or changes existing ones into new sounds.',
      'Searing Light': 'Ray deals 1d8/two levels damage (more against undead).',
      'Secret Chest': 'Hides expensive chest on Ethereal Plane; you retrieve it at will.',
      'Secret Page': 'Changes one page to hide its real content.',
      'Secure Shelter': 'Creates sturdy cottage.',
      'See Invisibility': 'Reveals <a href="glossary.html#_invisible">invisible</a> creatures or objects.',
      'Seeming': 'Changes appearance of 1 person per 2 levels.',
      'Sending': 'Delivers short message anywhere, instantly.',
      'Sepia Snake Sigil': 'Creates text symbol that immobilizes reader.',
      'Sequester': 'Subject is <a href="glossary.html#_invisible">invisible</a> to sight and <a href="spells/scrying.html#_scrying">scrying</a>; renders creature comatose.',
      'Shades': 'As <i><a href="spells/shadowConjuration.html#_shadow-conjuration">shadow conjuration</a></i>, but up to 8th level and 80% real.',
      'Shadow Conjuration': 'Mimics conjuration below 4th level, but only 20% real.',
      'Shadow Conjuration, Greater': 'As <i><a href="spells/shadowConjuration.html#_shadow-conjuration">shadow conjuration</a>, </i>but up to 6th level and 60% real.',
      'Shadow Evocation': 'Mimics evocation below 5th level, but only 20% real.',
      'Shadow Evocation, Greater': 'As <i><a href="spells/shadowEvocation.html#_shadow-evocation">shadow evocation</a>, </i>but up to 7th level and 60% real.',
      'Shadow Walk': 'Step into shadow to travel rapidly.',
      'Shambler': 'Creates 1d4+2 shambling mounds to fight for you.',
      'Shapechange': 'Transforms you into certain creatures, and lets you change forms once per round.',
      'Shatter': 'Sonic energy damages objects or creatures composed of crystal.',
      'Shield': 'Invisible disc gives +4 to <a href="combat.html#_armor-class">AC</a>, blocks <i><a href="spells/magicMissile.html#_magic-missile">magic missile</a>s.</i>',
      'Shield of Faith': 'Aura grants +2 or higher deflection bonus.',
      'Shield of Law': '+4 to <a href="combat.html#_armor-class">AC</a>, +4 resistance, and SR 25 against chaotic spells.',
      'Shield Other': 'You take half of subject\'s damage.',
      'Shillelagh': 'Cudgel or quarterstaff becomes +1 weapon (2d6 damage) for 1 min./level.',
      'Shocking Grasp': 'Touch delivers 1d6/level electricity damage (max 5d6).',
      'Shout': 'Deafens all within cone, 5d6 sonic damage.',
      'Shout, Greater': 'Devastating yell deals 10d6 sonic damage; stuns creatures.',
      'Shrink Item': 'Object shrinks to one-sixteenth size.',
      'Silence': 'Negates sound in 20-ft. radius.',
      'Silent Image': 'Creates minor illusion of your design.',
      'Simulacrum': 'Creates partially real double of a creature.',
      'Slay Living': 'Touch attack deals 12d6 +1 per level.',
      'Sleep': 'Puts 4 HD of creatures into magical slumber.',
      'Sleet Storm': 'Hampers vision and movement.',
      'Slow': 'One subject/level takes only one action/round, –1 to <a href="combat.html#_armor-class">AC</a>, <a href="combat.html#_reflex">Reflex</a> saves, and attack rolls.',
      'Snare': 'Creates a magic booby trap.',
      'Soften Earth and Stone': 'Turns stone to clay, or dirt to sand or mud.',
      'Solid Fog': 'Blocks vision and slows movement.',
      'Song of Discord': 'Forces targets to attack each other.',
      'Soul Bind': 'Traps newly dead soul to prevent <i><a href="spells/resurrection.html#_resurrection">resurrection</a></i>.',
      'Sound Burst': 'Deals 1d8 sonic damage to subjects; may stun them.',
      'Speak with Animals': 'You can communicate with animals.',
      'Speak with Dead': 'Corpse answers one question/two levels.',
      'Speak with Plants': 'You can talk to plants and plant creatures.',
      'Spectral Hand': 'Creates disembodied glowing hand to deliver touch attacks.',
      'Spell Immunity': 'Subject is immune to one spell per 4 levels.',
      'Spell Immunity, Greater': 'As <i><a href="spells/spellImmunity.html#_spell-immunity">spell immunity</a>, </i>but up to 8th-level spells.',
      'Spell Resistance': 'Subject gains SR 12 + level.',
      'Spellstaff': 'Stores one spell in wooden quarterstaff.',
      'Spell Turning': 'Reflect 1d4+6 spell levels back at caster.',
      'Spider Climb': 'Grants ability to walk on walls and ceilings.',
      'Spike Growth': 'Creatures in area take 1d4 damage, may be slowed<i>.</i>',
      'Spike Stones': 'Creatures in area take 1d8 damage, may also be slowed<i>.</i>',
      'Spiritual Weapon': 'Magic weapon attacks on its own.',
      'Stabilize': 'Cause a <a href="glossary.html#_dying">dying</a> creature to stabilize.',
      'Statue': 'Subject can become a statue at will.',
      'Status': 'Monitors condition, position of allies.',
      'Stinking Cloud': 'Nauseating vapors, 1 round/level.',
      'Stone Shape': 'Sculpts stone into any shape.',
      'Stoneskin': 'Grants DR 10/adamantine.',
      'Stone Tell': 'Talk to natural or worked stone.',
      'Stone to Flesh': 'Restores petrified creature.',
      'Storm of Vengeance': 'Storm rains acid, lightning, and hail.',
      'Suggestion': 'Compels a subject to follow stated course of action.',
      'Suggestion, Mass': 'As <i><a href="spells/suggestion.html#_suggestion">suggestion</a>, </i>affects 1 subject/level.',
      'Summon Instrument': 'Summons one musical instrument.',
      'Summon Monster I': '<i>(Evil creatures only.) </i>Summons extraplanar creature to fight for you.',
      'Summon Monster II': 'Summons elemental creature.',
      'Summon Monster III': '<i>(Evil creatures only.)</i> Summons extraplanar creature to fight for you.',
      'Summon Monster IV': 'Summons elemental creature to fight for you.',
      'Summon Monster V': 'Summons elemental creature to fight for you.',
      'Summon Monster VI': 'Summons elemental creature to fight for you.',
      'Summon Monster VII': 'Summons elemental creature to fight for you.',
      'Summon Monster VIII': 'Summons elemental creature to fight for you.',
      'Summon Monster IX': 'Summons extraplanar creature to fight for you.',
      'Summon Nature\'s Ally I': 'Summons creature to fight for you.',
      'Summon Nature\'s Ally II': 'Summons creature to fight for you.',
      'Summon Nature\'s Ally III': 'Summons creature to fight for you.',
      'Summon Nature\'s Ally IV': 'Summons creature to fight for you.',
      'Summon Nature\'s Ally V': 'Summons creature to fight.',
      'Summon Nature\'s Ally VI': 'Summons creature to fight.',
      'Summon Nature\'s Ally VII': 'Summons creature to fight.',
      'Summon Nature\'s Ally VIII': 'Summons creature to fight.',
      'Summon Nature\'s Ally IX': 'Summons creature to fight.',
      'Summon Swarm': 'Summons swarm of bats, rats, or spiders.',
      'Sunbeam': 'Beam blinds and deals 4d6 damage.',
      'Sunburst': 'Blinds all within 10 ft., deals 6d6 damage.',
      'Symbol of Death': 'Triggered rune kills nearby creatures.',
      'Symbol of Fear': 'Triggered rune panics nearby creatures.',
      'Symbol of Insanity': 'Triggered rune renders nearby creatures insane.',
      'Symbol of Pain': 'Triggered rune panics nearby creatures.',
      'Symbol of Persuasion': 'Triggered rune charms creatures.',
      'Symbol of Sleep': 'Triggered rune puts nearby creatures into catatonic slumber.',
      'Symbol of Stunning': 'Triggered rune stuns creatures.',
      'Symbol of Weakness': 'Triggered rune weakens creatures.',
      'Sympathetic Vibration': 'Deals 2d10 damage/round to freestanding structure.',
      'Sympathy': 'Object or location attracts certain creatures.',
      'Telekinesis': 'Moves object, attacks creature, or hurls object or creature.',
      'Telekinetic Sphere': 'As<i> <a href="spells/resilientSphere.html#_resilient-sphere">resilient sphere</a>, </i>but you move the sphere telekinetically.',
      'Telepathic Bond': 'Link lets allies communicate.',
      'Teleportation Circle': 'Teleports creatures inside circle.',
      'Teleport': 'Instantly transports you as far as 100 miles per level.',
      'Teleport, Greater': 'As <i><a href="spells/teleport.html#_teleport">teleport</a>, </i>but no range limit and no off-target arrival.',
      'Teleport Object': 'As <i><a href="spells/teleport.html#_teleport">teleport</a>, </i>but affects a touched object.',
      'Temporal Stasis': 'Puts subject into suspended animation.',
      'Time Stop': 'You act freely for 1d4+1 rounds.',
      'Tiny Hut': 'Creates shelter for 10 creatures.',
      'Tongues': 'Speak and understand any language.',
      'Touch of Fatigue': 'Touch attack fatigues target.',
      'Touch of Idiocy': 'Subject takes 1d6 penalty to <a href="gettingStarted.html#_intelligence">Int</a>, <a href="gettingStarted.html#_wisdom">Wis</a>, and <a href="gettingStarted.html#_charisma-new">Cha</a>.',
      'Transformation': 'You gain combat bonuses.',
      'Transmute Metal to Wood': 'Metal within 40 ft. becomes wood.',
      'Transmute Mud to Rock': 'Two 10-ft. cubes per level.',
      'Transmute Rock to Mud': 'Two 10-ft. cubes per level.',
      'Transport via Plants': 'Move instantly from one plant to another of the same kind.',
      'Trap the Soul': 'Imprisons subject within gem.',
      'Tree Shape': 'You look exactly like a tree for 1 hour/level.',
      'Tree Stride': 'Step from one tree to another far away.',
      'True Resurrection': 'As <i><a href="spells/resurrection.html#_resurrection">resurrection</a></i>, plus remains aren\'t needed.',
      'True Seeing': 'Lets you see all things as they really are.',
      'True Strike': '+20 on your next attack roll.',
      'Undeath to Death': 'Destroys 1d4/level HD of undead (max. 20d4).',
      'Undetectable Alignment': 'Conceals alignment for 24 hours.',
      'Unhallow': 'Designates location as unholy.',
      'Unholy Aura': '+4 to <a href="combat.html#_armor-class">AC</a>, +4 resistance, and SR 25 against good spells.',
      'Unholy Blight': 'Harms and sickens good creatures (1d8 damage/2 levels).',
      'Unseen Servant': 'Invisible force obeys your commands.',
      'Vampiric touch': 'Touch deals 1d6 damage/2 levels; caster gains damage as temporary hp.',
      'Veil': 'Changes appearance of a group of creatures.',
      'Ventriloquism': 'Throws voice for 1 min./level.',
      'Virtue': 'Subject gains 1 temporary hp.',
      'Vision': 'As <i><a href="spells/legendLore.html#_legend-lore">legend lore</a></i>, but quicker.',
      'Wail of the Banshee': 'Deals 10 damage/level to 1 creature/level.',
      'Wall of Fire': '2d4 fire damage to 10 ft. and 1d4 to 20 ft. Passing through wall deals 2d6 damage +1/level.',
      'Wall of Force': 'Wall is immune to damage.',
      'Wall of Ice': 'Ice plane creates wall or hemisphere creates dome.',
      'Wall of Iron': '30 hp/four levels; can topple onto foes.',
      'Wall of Stone': 'Creates a stone wall that can be shaped.',
      'Wall of Thorns': 'Thorns damage anyone who tries to pass.',
      'Warp Wood': 'Bends wood.',
      'Water Breathing': 'Subjects can breathe underwater.',
      'Water Walk': 'Subject treads on water as if solid.',
      'Waves of Exhaustion': 'Several targets become <a href="glossary.html#_exhausted">exhausted</a>.',
      'Waves of Fatigue': 'Several targets become <a href="glossary.html#_fatigued">fatigued</a>.',
      'Web': 'Fills 20-ft.-radius spread with sticky spiderwebs that can grapple foes and impair movement.',
      'Weird': 'As <i><a href="spells/phantasmalKiller.html#_phantasmal-killer">phantasmal killer</a>, </i>but affects all within 30 ft.',
      'Whirlwind': 'Cyclone deals damage and can pick up creatures.',
      'Whispering Wind': 'Sends a short message 1 mile/level.',
      'Wind Walk': 'You and your allies turn vaporous and travel fast.',
      'Wind Wall': 'Deflects arrows, smaller creatures, gasses.',
      'Wish': 'As <i><a href="spells/limitedWish.html#_limited-wish">limited wish</a>, </i>but with fewer limits.',
      'Wood Shape': 'Reshapes wooden objects to suit you.',
      'Word of Chaos': 'Kills, confuses<i>, </i>stuns, or deafens nonchaotic subjects.',
      'Word of Recall': 'Teleports you back to designated place.',
      'Zone of Silence': 'Keeps eavesdroppers from overhearing you.',
      'Zone of Truth': 'Subjects within range cannot lie.',
      'Absorbing Touch': 'Caster absorbs an item for 1 day/level.',
      'Accelerate Poison': 'Hastens targeted poison\'s onset.',
      'Acid Pit': 'Creates a pit with a layer of acid on the bottom.',
      'Alchemical Allocation': 'Gain potion\'s benefits without consuming it.',
      'Allfood': 'Turns item up to 5 lbs./level into food.',
      'Alter Winds': 'Increase/decrease strength of natural winds.',
      'Amplify Elixir': 'Empowers or extends the effects of any potion or elixir.',
      'Ant Haul': 'Triples carrying capacity of a creature.',
      'Aqueous Orb': 'Creates rolling sphere of water.',
      'Arcane Concordance': 'Grants metamagic to arcane spells.',
      'Arrow Eruption': 'Creates duplicates of killing arrow.',
      'Aspect of the Bear': '+2 AC and combat maneuver rolls.',
      'Aspect of the Falcon': 'Gives bonuses on <a href="../skills/perception.html#_perception">Perception</a> and ranged attacks.',
      'Aspect of the Stag': '+2 AC against attacks of opportunity and increases speed.',
      'Aspect of the Wolf': 'Subject gains +4 Str and Dex, and +2 bonus on trip attacks.',
      'Aura of Greater Courage': 'Increases strength of a paladin\'s aura of courage.',
      'Ball Lightning': 'Flying balls of lightning deal 3d6 electricity damage each.',
      'Banish Seeming': 'Dispels touched illusion or a creature\'s change in form.',
      'Bard\'s Escape': 'You and allies escape an emergency by teleporting to safety.',
      'Beguiling Gift': 'Subject immediately accepts an offered item and uses it.',
      'Bestow Grace': 'Subject gains bonus on saving throws equal to Cha modifier.',
      'Blaze of Glory': 'Last stand cures good creatures, hurts evil.',
      'Blessing of Courage and Life': 'Grants a +2 bonus on saves vs. fear and death.',
      'Blessing of Fervor': 'Gives allies a choice of benefits.',
      'Blessing of the Salamander': 'Subject gets fast healing 2, fire resistance 10, +2 CMD.',
      'Blood Biography': 'Learn about a creature with its blood.',
      'Bloodhound': 'Gives caster the scent special ability.',
      'Bloody Claws': 'Gives creature the ability to deal bleed damage with natural attacks.',
      'Bomber\'s Eye': 'Increases thrown weapon range; +1 attack.',
      'Borrow Fortune': '<i>(Oracle only.)</i> Retry attack or check, but do worse on next two.',
      'Borrow Skill': 'Make a skill check using another\'s ranks.',
      'Bow Spirit': 'Summons an invisible spirit that fires your arrows for you as a swift action.',
      'Brand': 'Creates permanent brand on target creature.',
      'Brand, Greater': 'As <i><a href="spells/brand.html#_brand">brand</a></i>, but brand glows when near your holy symbol.',
      'Break': 'Gives an object the broken condition.',
      'Brilliant Inspiration': 'Take best of two d20 rolls.',
      'Bristle': 'Trade natural armor bonus for a bonus on attacks with natural weapons.',
      'Burning Gaze': 'Inflict 1d6 fire damage to creature by looking at it.',
      'Burst Bonds': '1d6 damage/level (max 5d6) to restraints.',
      'Cacophonous Call': 'Nauseates target.',
      'Cacophonous Call, Mass': 'Nauseates multiple targets.',
      'Calcific Touch': 'Touch attack slows target, 1d4 Dex damage.',
      'Call Animal': 'Makes an animal come to you.',
      'Campfire Wall': 'Creates a shelter around a campfire.',
      'Castigate': 'Causes target to be shaken and cower.',
      'Castigate, Mass': 'As <i><a href="spells/castigate.html#_castigate">castigate</a></i>, but affects multiple creatures.',
      'Cast Out': 'Does 2d8 damage +1/level (max +15) to creature and dispels an effect.',
      'Challenge Evil': 'Sickens creature if it refuses to fight you.',
      'Chameleon Stride': 'Gives a +4 bonus on <a href="../skills/stealth.html#_stealth">Stealth</a> checks and concealment.',
      'Clashing Rocks': '20d6 damage to target creature.',
      'Cleanse': 'As <i><a href="../spells/heal.html#_heal">heal</a></i>, but only cures 4d8 damage +1/level (max +25).',
      'Cloak of Dreams': 'Causes living creatures within 5 ft. to fall asleep.',
      'Cloak of Shade': 'Reduces effects of intense sun exposure and environmental heat.',
      'Cloak of Winds': 'Creates a screen of wind around you.',
      'Confess': 'Creature answers question truthfully or takes 1d6 damage/two levels (max 5d6).',
      'Contagious Flame': 'Scorching rays cause 4d6 fire damage, then move on to new targets.',
      'Coordinated Effort': 'Grants allies a teamwork feat.',
      'Corruption Resistance': 'Protects creature against damage from alignment-based attacks.',
      'Coward\'s Lament': 'If subject doesn\'t attack you it receives a penalty.',
      'Crafter\'s Curse': 'Subject takes &#8211;5 on <a href="../skills/craft.html#_craft">Craft</a> skill checks.',
      'Crafter\'s Fortune': 'Subject gains +5 on next <a href="../skills/craft.html#_craft">Craft</a> check.',
      'Create Pit': 'Creates an extradimensional pit.',
      'Create Treasure Map': 'Creates treasure map out of a creature\'s corpse.',
      'Cup of Dust': 'Causes a creature to become dehydrated.',
      'Dancing Lantern': 'Animates a lantern that follows you.',
      'Deadly Finale': 'Deals 2d8 damage to multiple targets.',
      'Deafening Song Bolt': 'Blast of song deals 3d10 damage and deafens targets.',
      'Defile Armor': 'As <i><a href="spells/sanctifyArmor.html#_sanctify-armor">sanctify armor</a></i>, but gain DR 5/good when using judgment or smite.',
      'Deflection': 'Attacks that miss are redirected back to the source of the attack.',
      'Delayed Consumption': 'Extract doesn\'t come into effect until you want it to.',
      'Denounce': 'Worsens creatures\' attitudes.',
      'Detect Aberration': 'Detect presence of aberrations.',
      'Detonate': 'Inflicts 1d8/level energy damage to all creatures within 15 ft.',
      'Devolution': 'An eidolon temporarily loses 1 evolution +1/five levels.',
      'Discordant Blast': '3d6 sonic damage in 10-ft. burst or 30-ft. cone can also bull rush creatures.',
      'Divine Transfer': 'Transfer hit points and give DR/evil to target creature.',
      'Divine Vessel': '<i>(Oracle only.)</i> Change into a huge, otherworldly creature.',
      'Draconic Reservoir': 'Subject can absorb energy damage and enhance melee attacks with it.',
      'Dragon\'s Breath': 'Gives you a dragon\'s breath weapon.',
      'Dust of Twilight': 'Black particles extinguish light sources within area.',
      'Eagle Eye': 'Creates a magical sensor high above you.',
      'Elemental Aura': 'Creates an aura of energy around you.',
      'Elemental Speech': 'Enables you to speak to elementals and some creatures.',
      'Elemental Touch': 'Gain energy damage touch attack.',
      'Elude Time': 'Puts you in temporary suspended animation.',
      'Enemy Hammer': 'Allows you to telekinetically use a creature as a weapon.',
      'Enter Image': 'Transfers your consciousness to an object bearing your likeness.',
      'Euphoric Tranquility': 'Makes a creature friendly.',
      'Evolution Surge': 'Grants eidolon an evolution with 4 evolution points.',
      'Evolution Surge, Greater': 'Grants eidolon two evolutions with a total of 6 evolution points.',
      'Evolution Surge, Lesser': 'Grants eidolon an evolution with 2 evolution points.',
      'Expeditious Excavation': 'Moves 5-ft. cubes of earth.',
      'Expend': 'Wastes creatures\' limited use magical ability.',
      'Feast of Ashes': 'A target starves with an insatiable hunger.',
      'Feather Step': 'Subject ignores adverse movement effects in difficult terrain.',
      'Feather Step, Mass': 'As <i><a href="spells/featherStep.html#_feather-step">feather step</a></i>, but affects many targets rather than one.',
      'Fester': 'Gives subject SR 12 + your level vs. healing effects.',
      'Fester, Mass': 'As <i><a href="spells/fester.html#_fester">fester</a></i>, but affecting multiple targets.',
      'Fiery Body': 'You gain various fire-related powers.',
      'Firebrand': 'Allies gain <i><a href="../magicItems/weapons.html#_weapons-flaming">flaming</a></i> weapons, immunity to your fire spells, and a one-use ray of fire attack.',
      'Fire Breath': 'Exhale a cone of flame at will.',
      'Firefall': 'Causes fire to burst up, dealing 2d6 fire damage.',
      'Fire of Entanglement': 'Your ability to smite evil also entangles your foe.',
      'Fire of Judgment': 'Smited creature takes damage when it attacks.',
      'Fire of Vengeance': 'Smited creature takes 3d8 damage.',
      'Fire Snake': 'Creates a serpentine path of fire 5 ft. long/level that deals 1d6 fire damage/level.',
      'Flames of the Faithful': 'Gives weapon <i><a href="../magicItems/weapons.html#_weapons-flaming">flaming</a></i> property.',
      'Flare Burst': 'As <i><a href="../spells/flare.html#_flare">flare</a></i>, but affects all creatures in 10 ft.',
      'Fluid Form': 'Gain DR 10/slashing, increases reach 10 ft., and breathe water.',
      'Fly, Mass': 'One creature/level gains ability to fly.',
      'Foe to Friend': 'Redirect an enemy creature\'s attack.',
      'Follow Aura': 'Gain ability to follow the trail of the aura of an alignment.',
      'Fool\'s Forbiddance': 'Confuses enemies who come within a magical emanation centered on you.',
      'Forced Repentance': 'Target falls prone and confesses sins.',
      'Frozen Note': 'Paralyzes creatures listening to your song.',
      'Gallant Inspiration': '+2d4 bonus on failed attack roll or skill check.',
      'Getaway': 'Teleports you and select creatures to predetermined location.',
      'Geyser': 'Creates a geyser of boiling water.',
      'Ghostbane Dirge': 'Incorporeal creature takes half damage from nonmagical weapons.',
      'Ghostbane Dirge, Mass': 'As <i><a href="spells/ghostbaneDirge.html#_ghostbane-dirge">ghostbane dirge</a></i>, but affects multiple creatures.',
      'Glide': 'You take no falling damage and move 60 ft./round while falling.',
      'Grace': 'Movement doesn\'t provoke attacks of opportunity.',
      'Gravity Bow': 'Arrows do damage as though one size category bigger.',
      'Grove of Respite': 'Creates trees and a small spring.',
      'Guiding Star': 'Know approximate distance from where you cast this spell.',
      'Heroic Finale': 'Subject within range of your bardic performance can take an action.',
      'Hero\'s Defiance': 'Allows the use of lay on hands while falling unconscious.',
      'Hidden Speech': 'Gain +10 on <a href="../skills/bluff.html#_bluff">Bluff</a> to send secret messages.',
      'Hide Campsite': 'Hides all traces of your campsite.',
      'Holy Whisper': 'Whisper sickens evil creatures, gives good creatures bonuses.',
      'Honeyed Tongue': 'Roll 2 dice when using <a href="../skills/diplomacy.html#_diplomacy">Diplomacy</a>, take higher roll.',
      'Hungry Pit': 'As <i><a href="spells/createPit.html#_create-pit-">create pit</a></i>, but dealing 4d6 damage to those in it as it closes.',
      'Hunter\'s Eye': '+20 on <a href="../skills/perception.html#_perception">Perception</a> checks to locate a target.',
      'Hunter\'s Howl': 'Treat enemies as favored for 1 round/level.',
      'Hydraulic Push': 'Wave of water bull rushes an enemy.',
      'Hydraulic Torrent': 'Creates torrent of water that bull rushes any creature in its path.',
      'Ill Omen': 'Target rolls twice for checks and attacks and uses worst roll.',
      'Innocence': 'Gain +10 on <a href="../skills/bluff.html#_bluff">Bluff</a> checks to seem innocent.',
      'Instant Armor': 'Summon armor temporarily replacing your current attire.',
      'Instant Enemy': 'Target is treated as a favored enemy type of your choice.',
      'Invigorate': 'Temporarily relieves fatigue or exhaustion.',
      'Invigorate, Mass': 'As <i><a href="spells/invigorate.html#_invigorate">invigorate</a></i>, but multiple creatures.',
      'Jester\'s Jaunt': 'Teleport target within 30 ft. of itself.',
      'Keen Senses': 'Subject gains +2 <a href="../skills/perception.html#_perception">Perception</a>, low-light vision.',
      'King\'s Castle': 'Instantly switch places with a single ally.',
      'Knight\'s Calling': 'Forces target to move toward you and fight you.',
      'Lead Blades': 'Melee weapons damage as if one size bigger.',
      'Life Bubble': 'Protects creatures from sustained environmental effects.',
      'Light Lance': 'Creates a soaring beacon of light.',
      'Lily Pad Stride': 'Walk across water on moving lily pads.',
      'Lockjaw': 'Gives creature grab ability with a natural attack.',
      'Marks Of Forbiddance': 'Makes 2 creatures pass Will saves in order to attack each other.',
      'Mask Dweomer': 'Hides presence of a spell from d<i>etect magic</i>.',
      'Memory Lapse': 'Subject forgets events back to last turn.',
      'Moonstruck': 'Subject is enraged and confused.',
      'Nap Stack': 'Subjects only need 2 hours for a night\'s sleep, and can sleep even longer for more benefits.',
      'Natural Rhythm': '+1 on damage rolls with each hit (max +5).',
      'Nature\'s Exile': 'Gives subject &#8211;10 on <a href="../skills/survival.html#_survival">Survival</a> checks.',
      'Negate Aroma': 'Subject cannot be tracked by scent.',
      'Oath of Peace': 'Grants +5 AC and DR 10/evil, can\'t attack.',
      'Oracle\'s Burden': '<i>(Oracle only.)</i> Creature is affected by negative oracle\'s curse effects.',
      'Pain Strike': 'Inflicts 1d6 nonlethal damage 1 round/level.',
      'Pain Strike, Mass': 'As <i><a href="spells/painStrike.html#_pain-strike">pain strike</a></i>, but affects multiple creatures.',
      'Paladin\'s Sacrifice': 'Take the damage and effects for another creature.',
      'Perceive Cues': '+5 <a href="../skills/perception.html#_perception">Perception</a> and <a href="../skills/senseMotive.html#_sense-motive">Sense Motive</a> 10 min./level.',
      'Phantasmal Revenge': 'Ghost from corpse hunts killer.',
      'Phantasmal Web': 'Catches subjects in illusory web.',
      'Pied Piping': 'Compel similar creatures to follow you.',
      'Pillar of Life': 'Created pillar heals 2d8 + 1/level (max +20).',
      'Planar Adaptation': 'Resist harmful effects of other plane.',
      'Planar Adaptation, Mass': 'As <i><a href="spells/planarAdaptation.html#_planar-adaptation">planar adaptation</a></i>, but affects multiple creatures.',
      'Pox Pustules': 'Subject is sickened and has &#8211;4 Dex.',
      'Protective Spirit': 'Protects from attacks of opportunity.',
      'Purging Finale': 'Removes one negative effect.',
      'Purified Calling': 'Eidolon summoned is fully healed.',
      'Putrefy Food and Drink': 'Makes food and water inedible.',
      'Rally Point': 'Square gives good creatures bonuses.',
      'Rampart': 'Creates 5-ft.-thick earthen barrier.',
      'Rebuke': 'Foes take 1d8 damage/two caster levels (max 5d8).',
      'Rejuvenate Eidolon': 'As <i><a href="spells/rejuvenateEidolon.html#_rejuvenate-eidolon,-lesser">lesser rejuvenate eidolon</a></i>, but cures 3d10 damage +1/level (max +10).',
      'Rejuvenate Eidolon, Greater': 'As <i><a href="spells/rejuvenateEidolon.html#_rejuvenate-eidolon,-lesser">lesser rejuvenate eidolon</a></i>, but cures 5d10 damage +1/level (max +20).',
      'Rejuvenate Eidolon, Lesser': 'Eidolon cured 1d10 damage +1/level (max +5).',
      'Residual Tracking': 'Tell creature\'s appearance by footprint.',
      'Resounding Blow': 'Melee attack deals 1d6 more damage.',
      'Rest Eternal': 'Dead creature cannot be revived.',
      'Restful Sleep': 'Gain more hit points while sleeping.',
      'Resurgent Transformation': 'Gain second wind when close to death.',
      'Retribution': 'Recent attacker is afflicted with penalties.',
      'Reviving Finale': 'Allies cured 2d6 damage.',
      'Righteous Vigor': 'Boosts attack bonus with each hit.',
      'River of Wind': 'A stream of wind causes nonlethal damage and can knock down or push creatures.',
      'Sacred Bond': 'Cast touch healing spells from a distance.',
      'Sacrificial Oath': 'Take damage for an ally for many rounds.',
      'Saddle Surge': 'Bonus damage for moving on mount.',
      'Sanctify Armor': '+1 AC/four levels (max +5).',
      'Saving Finale': 'Subject rerolls failed saving throw.',
      'Scent Trail': 'Leave trail for allies to follow.',
      'Screech': 'Foes provoke attacks of opportunity.',
      'Sculpt Corpse': 'Makes corpse look like another creature.',
      'Seamantle': 'Sheathes you in protective water.',
      'Seek Thoughts': 'Detects thinking creatures\' thoughts.',
      'Shadow Projection': 'Temporarily become a shadow.',
      'Shared Wrath': 'As <i><a href="spells/wrath.html#_wrath">wrath</a></i>, but affects multiple creatures.',
      'Share Language': 'Subject understands chosen language.',
      'Share Senses': 'Perceive the world around your familiar.',
      'Shifting Sand': 'Creates difficult terrain and erases tracks, can carry along some creatures and objects.',
      'Sift': 'See area as though examining it.',
      'Sirocco': 'Hot wind does 4d6 damage, fatigues those damaged, and knocks creatures prone.',
      'Sleepwalk': 'Causes creature to move while asleep.',
      'Slipstream': 'Wave boosts creature\'s speed.',
      'Snake Staff': 'Transforms wood into snakes to fight for you.',
      'Solid Note': 'Creates tangible music note.',
      'Spark': 'Ignites flammable objects.',
      'Spiked Pit': 'As <i><a href="spells/createPit.html#_create-pit-">create pit</a></i>, but filled with spikes.',
      'Spiritual Ally': 'Creates a divine ally to aid you.',
      'Spite': 'Inflict touch spell upon creature that attacks you.',
      'Stay the Hand': 'Subject cannot attack with melee weapon.',
      'Stone Call': '2d6 damage to all creatures in area.',
      'Stone Fist': 'Your unarmed strikes are lethal.',
      'Stormbolts': '1d8 damage/level (max 20d8) to targets.',
      'Strong Jaw': 'Natural attacks damage as two sizes bigger.',
      'Stumble Gap': 'Small hole trips creatures.',
      'Stunning Finale': 'Stuns 3 creatures for 1 round.',
      'Suffocation': 'Target quickly suffocates to death.',
      'Suffocation, Mass': 'One creature/level suffocates to death.',
      'Summon Eidolon': 'Instantly summons your eidolon for duration of spell.',
      'Swarm Skin': 'Turns your body into a swarm of vermin.',
      'Thorn Body': 'Your attackers take 1d6 +1 damage/level.',
      'Threefold Aspect': 'Appear older or younger.',
      'Thundering Drums': '1d8 damage/level and knocked prone.',
      'Timely Inspiration': 'Gives bonus on failed check/attack.',
      'Tireless Pursuers': 'As <i><a href="spells/tirelessPursuit.html#_tireless-pursuit">tireless pursuit</a></i>, but affects many targets rather than one.',
      'Tireless Pursuit': 'Ignore fatigue while hustling.',
      'Touch of Gracelessness': 'Subject loses 1d6 + 1 Dex/two levels and is prone to falling down.',
      'Touch of the Sea': '<a href="../skills/swim.html#_swim">Swim</a> speed becomes 30 ft.',
      'Transmogrify': 'Change your eidolon\'s evolutions.',
      'Transmute Potion to Poison': 'Spit poison onto weapon after drinking potion.',
      'Treasure Stitching': 'Objects on cloth become embroidered.',
      'True Form': 'Removes polymorph effects.',
      'Tsunami': 'Huge wave damages and sweeps up all in its path.',
      'Twilight Knife': 'Floating knife attacks with you.',
      'Twin Form': 'Creates controllable duplicate of you.',
      'Unfetter': 'Remove distance restriction on eidolon.',
      'Universal Formula': 'Acts as any extract 3rd level or lower.',
      'Unwilling Shield': 'Subject shares wounds you receive.',
      'Unwitting Ally': 'Subject is considered ally for 1 round.',
      'Vanish': 'As <i><a href="../spells/invisibility.html#_invisibility">invisibility</a></i> for 1 round/level (5 max).',
      'Veil of Positive Energy': '+2 AC, +2 on saves vs. undead.',
      'Venomous Bolt': 'Arrow or bolt poisons target.',
      'Versatile Weapon': 'Weapon bypasses some DR.',
      'Vomit Swarm': 'Produces a spider swarm that fights for you.',
      'Vortex': 'Creates a whirlpool in water.',
      'Wake of Light': 'Magical trail aids good creatures, hinders evil ones.',
      'Wall of Lava': 'Wall damages foes that try to enter, periodically launches lava at nearby targets.',
      'Wall of Suppression': 'Creates wall that disables magic.',
      'Wandering Star Motes': 'Outlines subject and produces light as a sunrod.',
      'Ward the Faithful': 'Creatures of same faith gain bonuses to AC and on saving throws.',
      'Weapon of Awe': 'Weapon gets +2 on damage rolls.',
      'Winds of Vengeance': 'Gives you the ability to fly and attack with wind.',
      'World Wave': 'Earth moves you across distances.',
      'Wrathful Mantle': 'Subject shines and gets +1/four levels on all saves.',
      'Wrath': '+1 attack and damage against target creature.',
      'Ablative Barrier': 'Surrounds the target with layers of force.',
      'Absorb Toxicity': 'You become immune to diseases and toxins, absorb one, and then spread it to others.',
      'Abundant Ammunition': 'Replaces nonmagical ammunition every round.',
      'Adjuring Step': 'You can move slowly and safely and still cast spells, until you move quickly, make an attack, or cast a harmful spell.',
      'Adoration': 'You gain a bonus on <a href="/pathfinderRPG/prd/skills/diplomacy.html#_diplomacy">Diplomacy</a> checks and performance combat checks.',
      'Air Bubble': 'Creates a small pocket of air around your head or an object.',
      'Air Walk, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/airWalk.html#_air-walk">air walk</a></i>, but you may divide the duration among creatures touched.',
      'Animal Aspect': 'You gain some of the beneficial qualities of an animal.',
      'Animal Aspect, Greater': 'As <i><a href="spells/animalAspect.html#_animal-aspect">animal aspect</a></i>, but you gain two animal qualities.',
      'Ant Haul, Communal': 'As <i><a href="/pathfinderRPG/prd/advanced/spells/antHaul.html#_ant-haul-">ant haul</a></i>, but you may divide the duration among creatures touched.',
      'Arcane Cannon': 'Your focus becomes a magical cannon that fires on its own.',
      'Bestow Weapon Proficiency': 'Grants a creature proficiency in a single weapon for short period of time.',
      'Blistering Invective': 'Make an <a href="/pathfinderRPG/prd/skills/intimidate.html#_intimidate">Intimidate</a> check against all foes within 30 feet; those demoralized also take fire damage.',
      'Bowstaff': 'A shortbow may double as a club, or a longbow as a quarterstaff.',
      'Brow Gasher': 'Slashing weapon deals bleed damage to an opponent\'s head.',
      'Bullet Shield': 'You gain a +4 deflection bonus to AC against firearm attacks.',
      'Burst of Speed': 'You gain increased speed, and your movement ignores attacks of opportunity and allows you to move through the space of creatures larger than you are.',
      'Caging Bomb Admixture': 'Your bombs create a cage of force that traps creatures inside the bomb\'s splash radius.',
      'Certain Grip': 'You gain a +4 competence bonus on <a href="/pathfinderRPG/prd/skills/acrobatics.html#_acrobatics">Acrobatics</a> and <a href="/pathfinderRPG/prd/skills/climb.html#_climb">Climb</a> checks and to CMD.',
      'Chain of Perdition': 'Creates a floating chain of force.',
      'Companion Mind Link': 'You can talk with your animal companion, and can handle it with supernatural ease.',
      'Compel Hostility': 'Compels opponents to attack you instead of your allies.',
      'Damp Powder': 'Ruins ammunition loaded in the targeted firearm.',
      'Darkvision, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/darkvision.html#_darkvision">darkvision</a></i>, but you may divide the duration among creatures touched.',
      'Daybreak Arrow': 'Targeted ammunition exudes radiant energy.',
      'Deadeye\'s Lore': 'Gain a +4 bonus on <a href="/pathfinderRPG/prd/skills/survival.html#_survival">Survival</a> and move full speed while tracking.',
      'Deadly Juggernaut': 'Your might increases with every kill you make.',
      'Debilitating Portent': 'Inflicts an ill fate on a creature, halving its damage when it attacks or casts a spell',
      'Delay Poison, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/delayPoison.html#_delay-poison">delay poison</a></i>, but you may divide the duration among creatures touched.',
      'Destabilize Powder': 'Ammunition in the targeted firearm is prone to misfire.',
      'Discovery Torch': 'Object touched emanates bright light, granting <a href="/pathfinderRPG/prd/skills/perception.html#_perception">Perception</a> and <a href="/pathfinderRPG/prd/skills/senseMotive.html#_sense-motive">Sense Motive</a> bonuses.',
      'Divine Arrow': 'Imbues a projectile with holy energy.',
      'Dust Form': 'You become an incorporeal creature of dust for a short period of time.',
      'Effortless Armor': 'Armor you wear no longer slows your speed.',
      'Endure Elements, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/endureElements.html#_endure-elements">endure elements</a></i>, but you may divide the duration among creatures touched.',
      'Energy Siege Shot': 'A Large siege engine deals energy damage that you designate with other effects depending on the type of energy you choose.',
      'Energy Siege Shot, Greater': 'As <i><a href="spells/energySiegeShot.html#_energy-siege-shot">energy siege shot</a></i>, but you can affect any size siege engine.',
      'Fabricate Bullets': 'Converts 1 pound of metal into ammunition.',
      'Fiery Shuriken': 'Calls forth several fiery projectiles ready to be flung at opponents.',
      'Find Quarry': 'You can sense whether a particular creature is within 20 miles of your location.',
      'Flash Fire': 'Ammunition in the targeted firearm creates a tremendous flash capable of blinding the weapon\'s bearer and those around him.',
      'Forest Friend': 'Plants in a forested area become helpful instead of hindering you and your allies.',
      'Frightful Aspect': 'You take on a terrifying, Large-sized form of yourself and emit an aura that causes creatures to become shaken or frightened.',
      'Frost Fall': 'The area is covered in a chilling frost.',
      'Haunted Fey Aspect': 'You surround yourself with disturbing illusions.',
      'Healing Thief': 'You siphon half of all magical healing that the targeted creature receives.',
      'Heroic Invocation': 'Grants a number of creatures bonuses on attacks and damage, temporary hit points, and immunity to fear and charm effects.',
      'Hostile Juxtaposition': 'You create a dimensional link with a targeted creature, and switch spots with it.',
      'Hostile Juxtaposition, Greater': 'You may target one creature for every four of your caster levels.',
      'Hostile Levitation': 'Levitates the targeted creature up off the ground.',
      'Illusion of Calm': 'You appear to be standing still, even when you take some actions.',
      'Instrument of Agony': 'Weapon exudes divine fury, granting a bonus on <a href="/pathfinderRPG/prd/skills/intimidate.html#_intimidate">Intimidate</a> checks.',
      'Jolting Portent': 'You inflict a vengeful fate on a creature, dealing electricity damage each time it attacks or casts a spell.',
      'Judgment Light': 'You gain an additional effect while a judgment is active.',
      'Jury-Rig': 'Removes the broken condition from the targeted object.',
      'Kinetic Reverberation': 'Channels the force of an enemy\'s attack back into its weapon.',
      'Languid Bomb Admixture': 'Empowers bombs you throw to cause fatigue in those directly hit or splashed by the bomb.',
      'Liberating Command': 'Target makes an <a href="/pathfinderRPG/prd/skills/escapeArtist.html#_escape-artist">Escape Artist</a> check as an immediate action and gains a bonus on it.',
      'Life Conduit': 'You are bound even tighter to your eidolon than normal, and may share hit points with it through your life link ability.',
      'Life Conduit, Greater': 'You transfer 3d6 hit points to your eidolon as a swift action.',
      'Life Conduit, Improved': 'Transfers 2d6 hit points to your eidolon as a swift action.',
      'Lightning Lash Bomb Admixture': 'Empowers bombs you throw with a ward that deals lightning damage each time those damaged by the bomb move more than 5 feet.',
      'Litany of Defense': 'Doubles armor\'s enhancement bonus.',
      'Litany of Eloquence': 'Fascinates a single creature for 1 round.',
      'Litany of Entanglement': 'Entangles a creature for 1 round.',
      'Litany of Escape': 'Teleports a friend out of a grapple.',
      'Litany of Madness': 'A single target is confused for at least 1 round.',
      'Litany of Righteousness': 'A single evil creature takes more damage from creatures with a good aura.',
      'Litany of Sight': 'You can see invisible creatures and objects within 30 feet of you.',
      'Litany of Sloth': 'Single target cannot make attacks of opportunity for 1 round.',
      'Litany of Thunder': 'A single target is deafened until the condition is removed, and is confused for 1 round.',
      'Litany of Vengeance': 'Allies attacking the target of the spell gain a +5 bonus on damage rolls for 1 round.',
      'Litany of Warding': 'You gain two additional attacks of opportunity for 1 round.',
      'Litany of Weakness': 'Single target is fatigued for 1 round.',
      'Locate Weakness': 'You roll damage twice when you roll damage for a critical hit and take the best damage.',
      'Lock Gaze': 'Compels the target to look only at you for the duration of the spell.',
      'Longshot': 'Grants a +10-foot bonus to the range increment for any ranged weapon fired.',
      'Magic Siege Engine': 'Siege gains +1 on targeting and damage rolls.',
      'Magic Siege Engine, Greater': 'Siege engine gains +1 on targeting and damage rolls for every four caster levels.',
      'Mask Dweomer, Communal': 'As <i><a href="/pathfinderRPG/prd/advanced/spells/maskDweomer.html#_mask-dweomer">mask dweomer</a></i>, but you may divide the duration among creatures touched.',
      'Mind Blank, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/mindBlank.html#_mind-blank">mind blank</a></i>, but you may divide the duration among creatures touched.',
      'Mirror Strike': 'You may strike multiple opponents with a single attack.',
      'Moment of Greatness': 'Doubles a morale bonus.',
      'Mount, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/mount.html#_mount">mount</a></i>, but you may divide the duration among creatures touched.',
      'Mutagenic Touch': 'You can pass a weaker version of your mutagen to another creature.',
      'Named Bullet': 'Imbues ammunition with accuracy against a specific creature type.',
      'Named Bullet, Greater': 'As <i><a href="spells/namedBullet.html#_named-bullet">named bullet</a></i>, but deals 2 points of damage for every caster level.',
      'Negative Reaction': 'Targeted creature may not positively influence anyone.',
      'Nondetection, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/nondetection.html#_nondetection">nondetection</a></i>, but you may divide the duration among creatures touched.',
      'Obsidian Flow': 'Converts the surface of the ground into molten glass.',
      'Peacebond': 'Locks a weapon in place on the target\'s body.',
      'Pellet Blast': 'Creates an explosion of conjured metal pellets.',
      'Phantom Chariot': 'Conjures a quasi-real heavy chariot pulled by four horses.',
      'Phantom Driver': 'Conjures a phantom to drive vehicles.',
      'Phantom Steed, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/phantomSteed.html#_phantom-steed">phantom steed</a></i>, but you may divide the duration among creatures touched.',
      'Pilfering Hand': 'You may seize an object or manipulate it from afar.',
      'Protection from Arrows, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromArrows.html#_protection-from-arrows">protection from arrows</a></i>, but you may divide the duration among creatures touched.',
      'Protection from Chaos, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromChaos.html#_protection-from-chaos">protection from chaos</a></i>, but you may divide the duration among creatures touched.',
      'Protection from Energy, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromEnergy.html#_protection-from-energy">protection from energy</a></i>, but you may divide the duration among creatures touched.',
      'Protection from Evil, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromEvil.html#_protection-from-evil">protection from evil</a></i>, but you may divide the duration among creatures touched.',
      'Protection from Good, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromGood.html#_protection-from-good">protection from good</a></i>, but you may divide the duration among creatures touched.',
      'Protection from Law, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/protectionFromLaw.html#_protection-from-law">protection from law</a></i>, but you may divide the duration among creatures touched.',
      'Pup Shape': 'Transforms a single animal or magical beast into a younger and cuter version of itself for a short period of time.',
      'Qualm': 'Target gains penalties on ability checks, skill checks, and concentration checks until it spends an entire round doing nothing.',
      'Recoil Fire': 'Ammunition in the targeted firearm generates excessive recoil.',
      'Reinforce Armaments': 'Temporarily mitigates the fragile quality in targeted weapon or armor.',
      'Reinforce Armaments, Communal': 'As <i><a href="spells/reinforceArmaments.html#_reinforce-armaments">reinforce armaments</a></i>, but you may divide the spell\'s duration among objects touched.',
      'Reloading Hands': 'Loads a single shot into your weapon every round.',
      'Resinous Skin': 'You gain DR 5/piercing and +4 to CMD against disarm attempts.',
      'Resist Energy, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/resistEnergy.html#_resist-energy">resist energy</a></i>, but you may divide the duration among creatures touched.',
      'Returning Weapon': 'Grants a weapon the <i><a href="/pathfinderRPG/prd/magicItems/weapons.html#_weapons-returning">returning</a></i> special weapon quality.',
      'Returning Weapon, Communal': 'As <i><a href="spells/returningWeapon.html#_returning-weapon">returning weapon</a></i>, but you may divide the duration among weapons touched.',
      'Ricochet Shot': 'Imbues a projectile weapon to give its ammunition the ability to ricochet.',
      'See Alignment': 'Pick an alignment; in your sight, creatures and items with that alignment emit a ghostly radiance.',
      'Shadow Bomb Admixture': 'Empowers bombs you throw to cover the target with a shadowy substance that grants it concealment and limits its vision.',
      'Share Language, Communal': 'As <i><a href="/pathfinderRPG/prd/advanced/spells/shareLanguage.html#_share-language-">share language</a></i>, but you may divide the duration among creatures touched.',
      'Shocking Image': 'As <i><a href="/pathfinderRPG/prd/spells/mirrorImage.html#_mirror-image">mirror image</a></i>, but the duplicates emit electrical damage when destroyed.',
      'Shock Shield': 'A shield of force protects you until you dismiss it in an explosion of electricity.',
      'Siege of Trees': 'Transforms Large trees into arboreal catapults of the same size.',
      'Siege of Trees, Greater': 'As <i><a href="spells/siegeOfTrees.html#_siege-of-trees">siege of trees</a></i>, but can transform Huge and Gargantuan trees into arboreal catapults of the same size.',
      'Spell Immunity, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/spellImmunity.html#_spell-immunity">spell immunity</a></i>, but you may divide the duration among creatures touched.',
      'Spell Immunity, Greater Communal': 'As <i><a href="/pathfinderRPG/prd/spells/spellImmunity.html#_spell-immunity-greater">greater spell immunity</a></i>, but you may divide the duration among creatures touched.',
      'Spider Climb, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/spiderClimb.html#_spider-climb">spider climb</a></i>, but you may divide the duration among creatures touched.',
      'Spontaneous Immolation': 'Target takes 3d6 points of fire damage and catches on fire.',
      'Stabilize Powder': 'Ammunition in the targeted firearm is less likely to misfire.',
      'Stoneskin, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/stoneskin.html#_stoneskin">stoneskin</a></i>, but you may divide the duration among creatures touched.',
      'Summoner Conduit': 'The target takes damage whenever its summoned creature does.',
      'Sun Metal': 'Weapon touched bursts into flames.',
      'Symbol of Striking': 'As <i><a href="/pathfinderRPG/prd/spells/symbolOfDeath.html#_symbol-of-death">symbol of death</a></i>, but fills a 5-foot square.',
      'Tactical Acumen': 'You gain an additional +1 on attack rolls or to AC due to battlefield positioning.',
      'Targeted Bomb Admixture': 'Empowers bombs you throw to deal more damage to a single creature.',
      'Tar Pool': 'Converts the top layer of the ground into hot tar.',
      'Telekinetic Assembly': 'Assembles a siege engine using 1 fewer worker for every two caster levels.',
      'Telekinetic Charge': 'Launches an ally through the air.',
      'Terrain Bond': 'Treat the terrain you are in as a favored terrain for the spell\'s duration.',
      'Thunder Fire': 'Ammunition in the targeted firearm deafens opponents.',
      'Tongues, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/tongues.html#_tongues">tongues</a></i>, but you may divide the duration among creatures touched.',
      'Touch Injection': 'You can deliver an infusion, elixir, poison, or potion as a touch attack.',
      'Twisted Space': 'Targeted creature\'s attacks target a random square instead of the intended target.',
      'Unerring Weapon': 'Grants a +2 bonus, +1 per four caster levels, on attack rolls to confirm a critical hit.',
      'Viper Bomb Admixture': 'Empowers bombs you throw to summon poisonous biting vipers that bite those hit or splashed by the bomb.',
      'Walk through Space': 'You can spend a move action to teleport 30 feet or to stand while prone without provoking attacks of opportunity.',
      'Warding Weapon': 'The weapon you use for the focus of this spell defends you, allowing you to cast spells without provoking attacks of opportunity.',
      'Water Walk, Communal': 'As <i><a href="/pathfinderRPG/prd/spells/waterWalk.html#_water-walk">water walk</a></i>, but you may divide the duration among creatures touched.',
      'Weaken Powder': 'Targeted firearm\'s ammunition halves the firearm\'s range and imposes a –2 penalty on damage rolls.',
      'Wilderness Soldiers': 'Nearby plants aid you in combat.',
      'Wreath of Blades': 'Four mithral daggers speed around you, attacking nearby creatures and protecting your spellcasting from attacks of opportunity.',
    },
};
